export interface IFacebookInsightData {
	value: any;
	end_time: string;
}

export interface IFacebookInsight {
	name: FacebookInsightMetric;
	period: FacebookInsightPeriod;
	values: IFacebookInsightData[];
	title?: any;
	description: string;
	id: string;
}

export interface IFacebookInsightPaging {
	previous: string;
	next: string;
}

export interface IFacebookInsightResponse {
	data: IFacebookInsight[];
	paging: IFacebookInsightPaging;
}

export enum FacebookInsightMetric {
  //Page Content
  PAGE_TAB_VIEWS_LOGIN_TOP_UNIQUE = "page_tab_views_login_top_unique",
  PAGE_TAB_VIEWS_LOGIN_TOP = "page_tab_views_login_top",
  PAGE_TAB_VIEWS_LOGOUT_TOP = "page_tab_views_logout_top",
  //Page CTA Clicks
  PAGE_TOTAL_ACTIONS = "page_total_actions",
  PAGE_CTA_CLICKS_LOGGED_IN_TOTAL = "page_cta_clicks_logged_in_total",
  PAGE_CTA_CLICKS_LOGGED_IN_UNIQUE = "page_cta_clicks_logged_in_unique",
  PAGE_CTA_CLICKS_BY_SITE_LOGGED_IN_UNIQUE = "page_cta_clicks_by_site_logged_in_unique",
  PAGE_CTA_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE = "page_cta_clicks_by_age_gender_logged_in_unique",
  PAGE_CTA_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE = "page_cta_clicks_logged_in_by_country_unique",
  PAGE_CTA_CLICKS_LOGGED_IN_BY_CITY_UNIQUE = "page_cta_clicks_logged_in_by_city_unique",
  PAGE_CALL_PHONE_CLICKS_LOGGED_IN_UNIQUE = "page_call_phone_clicks_logged_in_unique",
  PAGE_CALL_PHONE_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE = "page_call_phone_clicks_by_age_gender_logged_in_unique",
  PAGE_CALL_PHONE_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE = "page_call_phone_clicks_logged_in_by_country_unique",
  PAGE_CALL_PHONE_CLICKS_LOGGED_IN_BY_CITY_UNIQUE = "page_call_phone_clicks_logged_in_by_city_unique",
  PAGE_CALL_PHONE_CLICKS_BY_SITE_LOGGED_IN_UNIQUE = "page_call_phone_clicks_by_site_logged_in_unique",
  PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_UNIQUE = "page_get_directions_clicks_logged_in_unique",
  PAGE_GET_DIRECTIONS_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE = "page_get_directions_clicks_by_age_gender_logged_in_unique",
  PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE = "page_get_directions_clicks_logged_in_by_country_unique",
  PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_BY_CITY_UNIQUE = "page_get_directions_clicks_logged_in_by_city_unique",
  PAGE_GET_DIRECTIONS_CLICKS_BY_SITE_LOGGED_IN_UNIQUE = "page_get_directions_clicks_by_site_logged_in_unique",
  PAGE_WEBSITE_CLICKS_LOGGED_IN_UNIQUE = "page_website_clicks_logged_in_unique",
  PAGE_WEBSITE_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE = "page_website_clicks_by_age_gender_logged_in_unique",
  PAGE_WEBSITE_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE = "page_website_clicks_logged_in_by_country_unique",
  PAGE_WEBSITE_CLICKS_LOGGED_IN_BY_CITY_UNIQUE = "page_website_clicks_logged_in_by_city_unique",
  PAGE_WEBSITE_CLICKS_BY_SITE_LOGGED_IN_UNIQUE = "page_website_clicks_by_site_logged_in_unique",
  //Page Engagement
  PAGE_ENGAGED_USERS = "page_engaged_users",
  PAGE_POST_ENGAGEMENTS = "page_post_engagements",
  PAGE_CONSUMPTIONS = "page_consumptions",
  PAGE_CONSUMPTIONS_UNIQUE = "page_consumptions_unique",
  PAGE_CONSUMPTIONS_BY_CONSUMPTION_TYPE = "page_consumptions_by_consumption_type",
  PAGE_CONSUMPTIONS_BY_CONSUMPTION_TYPE_UNIQUE = "page_consumptions_by_consumption_type_unique",
  PAGE_PLACES_CHECKIN_TOTAL = "page_places_checkin_total",
  PAGE_PLACES_CHECKIN_TOTAL_UNIQUE = "page_places_checkin_total_unique",
  PAGE_PLACES_CHECKIN_MOBILE = "page_places_checkin_mobile",
  PAGE_PLACES_CHECKIN_MOBILE_UNIQUE = "page_places_checkin_mobile_unique",
  PAGE_PLACES_CHECKINS_BY_AGE_GENDER = "page_places_checkins_by_age_gender",
  PAGE_PLACES_CHECKINS_BY_LOCALE = "page_places_checkins_by_locale",
  PAGE_PLACES_CHECKINS_BY_COUNTRY = "page_places_checkins_by_country",
  PAGE_NEGATIVE_FEEDBACK = "page_negative_feedback",
  PAGE_NEGATIVE_FEEDBACK_UNIQUE = "page_negative_feedback_unique",
  PAGE_NEGATIVE_FEEDBACK_BY_TYPE = "page_negative_feedback_by_type",
  PAGE_NEGATIVE_FEEDBACK_BY_TYPE_UNIQUE = "page_negative_feedback_by_type_unique",
  PAGE_POSITIVE_FEEDBACK_BY_TYPE = "page_positive_feedback_by_type",
  PAGE_POSITIVE_FEEDBACK_BY_TYPE_UNIQUE = "page_positive_feedback_by_type_unique",
  PAGE_FANS_ONLINE = "page_fans_online",
  PAGE_FANS_ONLINE_PER_DAY = "page_fans_online_per_day",
  PAGE_FAN_ADDS_BY_PAID_NON_PAID_UNIQUE = "page_fan_adds_by_paid_non_paid_unique",
  //Page Impressions
  PAGE_IMPRESSIONS = "page_impressions",
  PAGE_IMPRESSIONS_UNIQUE = "page_impressions_unique",
  PAGE_IMPRESSIONS_PAID = "page_impressions_paid",
  PAGE_IMPRESSIONS_PAID_UNIQUE = "page_impressions_paid_unique",
  PAGE_IMPRESSIONS_ORGANIC_V2 = "page_impressions_organic_v2",
  PAGE_IMPRESSIONS_ORGANIC_UNIQUE_V2 = "page_impressions_organic_unique_v2",
  PAGE_IMPRESSIONS_VIRAL = "page_impressions_viral",
  PAGE_IMPRESSIONS_VIRAL_UNIQUE = "page_impressions_viral_unique",
  PAGE_IMPRESSIONS_NONVIRAL = "page_impressions_nonviral",
  PAGE_IMPRESSIONS_NONVIRAL_UNIQUE = "page_impressions_nonviral_unique",
  PAGE_IMPRESSIONS_BY_STORY_TYPE = "page_impressions_by_story_type",
  PAGE_IMPRESSIONS_BY_STORY_TYPE_UNIQUE = "page_impressions_by_story_type_unique",
  PAGE_IMPRESSIONS_BY_CITY_UNIQUE = "page_impressions_by_city_unique",
  PAGE_IMPRESSIONS_BY_COUNTRY_UNIQUE = "page_impressions_by_country_unique",
  PAGE_IMPRESSIONS_BY_LOCALE_UNIQUE = "page_impressions_by_locale_unique",
  PAGE_IMPRESSIONS_BY_AGE_GENDER_UNIQUE = "page_impressions_by_age_gender_unique",
  PAGE_IMPRESSIONS_FREQUENCY_DISTRIBUTION = "page_impressions_frequency_distribution",
  PAGE_IMPRESSIONS_VIRAL_FREQUENCY_DISTRIBUTION = "page_impressions_viral_frequency_distribution",
  //Page Posts
  PAGE_POSTS_IMPRESSIONS = "page_posts_impressions",
  PAGE_POSTS_IMPRESSIONS_UNIQUE = "page_posts_impressions_unique",
  PAGE_POSTS_IMPRESSIONS_PAID = "page_posts_impressions_paid",
  PAGE_POSTS_IMPRESSIONS_PAID_UNIQUE = "page_posts_impressions_paid_unique",
  PAGE_POSTS_IMPRESSIONS_ORGANIC = "page_posts_impressions_organic",
  PAGE_POSTS_IMPRESSIONS_ORGANIC_UNIQUE = "page_posts_impressions_organic_unique",
  PAGE_POSTS_SERVED_IMPRESSIONS_ORGANIC_UNIQUE = "page_posts_served_impressions_organic_unique",
  PAGE_POSTS_IMPRESSIONS_VIRAL = "page_posts_impressions_viral",
  PAGE_POSTS_IMPRESSIONS_VIRAL_UNIQUE = "page_posts_impressions_viral_unique",
  PAGE_POSTS_IMPRESSIONS_NONVIRAL = "page_posts_impressions_nonviral",
  PAGE_POSTS_IMPRESSIONS_NONVIRAL_UNIQUE = "page_posts_impressions_nonviral_unique",
  PAGE_POSTS_IMPRESSIONS_FREQUENCY_DISTRIBUTION = "page_posts_impressions_frequency_distribution",
  //Page Post Engagement
  POST_ENGAGED_USERS = "post_engaged_users",
  POST_NEGATIVE_FEEDBACK = "post_negative_feedback",
  POST_NEGATIVE_FEEDBACK_UNIQUE = "post_negative_feedback_unique",
  POST_NEGATIVE_FEEDBACK_BY_TYPE = "post_negative_feedback_by_type",
  POST_NEGATIVE_FEEDBACK_BY_TYPE_UNIQUE = "post_negative_feedback_by_type_unique",
  POST_ENGAGED_FAN = "post_engaged_fan",
  POST_CLICKS = "post_clicks",
  POST_CLICKS_UNIQUE = "post_clicks_unique",
  POST_CLICKS_BY_TYPE = "post_clicks_by_type",
  POST_CLICKS_BY_TYPE_UNIQUE = "post_clicks_by_type_unique",
  //Page Post Impressions
  POST_IMPRESSIONS = "post_impressions",
  POST_IMPRESSIONS_UNIQUE = "post_impressions_unique",
  POST_IMPRESSIONS_PAID = "post_impressions_paid",
  POST_IMPRESSIONS_PAID_UNIQUE = "post_impressions_paid_unique",
  POST_IMPRESSIONS_FAN = "post_impressions_fan",
  POST_IMPRESSIONS_FAN_UNIQUE = "post_impressions_fan_unique",
  POST_IMPRESSIONS_FAN_PAID = "post_impressions_fan_paid",
  POST_IMPRESSIONS_FAN_PAID_UNIQUE = "post_impressions_fan_paid_unique",
  POST_IMPRESSIONS_ORGANIC = "post_impressions_organic",
  POST_IMPRESSIONS_ORGANIC_UNIQUE = "post_impressions_organic_unique",
  POST_IMPRESSIONS_VIRAL = "post_impressions_viral",
  POST_IMPRESSIONS_VIRAL_UNIQUE = "post_impressions_viral_unique",
  POST_IMPRESSIONS_NONVIRAL = "post_impressions_nonviral",
  POST_IMPRESSIONS_NONVIRAL_UNIQUE = "post_impressions_nonviral_unique",
  POST_IMPRESSIONS_BY_STORY_TYPE = "post_impressions_by_story_type",
  POST_IMPRESSIONS_BY_STORY_TYPE_UNIQUE = "post_impressions_by_story_type_unique",
  //Page Post Reactions
  POST_REACTIONS_LIKE_TOTAL = "post_reactions_like_total",
  POST_REACTIONS_LOVE_TOTAL = "post_reactions_love_total",
  POST_REACTIONS_WOW_TOTAL = "post_reactions_wow_total",
  POST_REACTIONS_HAHA_TOTAL = "post_reactions_haha_total",
  POST_REACTIONS_SORRY_TOTAL = "post_reactions_sorry_total",
  POST_REACTIONS_ANGER_TOTAL = "post_reactions_anger_total",
  POST_REACTIONS_BY_TYPE_TOTAL = "post_reactions_by_type_total",
  //Page Reactions
  PAGE_ACTIONS_POST_REACTIONS_LIKE_TOTAL = "page_actions_post_reactions_like_total",
  PAGE_ACTIONS_POST_REACTIONS_LOVE_TOTAL = "page_actions_post_reactions_love_total",
  PAGE_ACTIONS_POST_REACTIONS_WOW_TOTAL = "page_actions_post_reactions_wow_total",
  PAGE_ACTIONS_POST_REACTIONS_HAHA_TOTAL = "page_actions_post_reactions_haha_total",
  PAGE_ACTIONS_POST_REACTIONS_SORRY_TOTAL = "page_actions_post_reactions_sorry_total",
  PAGE_ACTIONS_POST_REACTIONS_ANGER_TOTAL = "page_actions_post_reactions_anger_total",
  PAGE_ACTIONS_POST_REACTIONS_TOTAL = "page_actions_post_reactions_total",
  //Page User Demographics
  PAGE_FANS = "page_fans",
  PAGE_FANS_LOCALE = "page_fans_locale",
  PAGE_FANS_CITY = "page_fans_city",
  PAGE_FANS_COUNTRY = "page_fans_country",
  PAGE_FANS_GENDER_AGE = "page_fans_gender_age",
  PAGE_FAN_ADDS = "page_fan_adds",
  PAGE_FAN_ADDS_UNIQUE = "page_fan_adds_unique",
  PAGE_FANS_BY_LIKE_SOURCE = "page_fans_by_like_source",
  PAGE_FANS_BY_LIKE_SOURCE_UNIQUE = "page_fans_by_like_source_unique",
  PAGE_FAN_REMOVES = "page_fan_removes",
  PAGE_FAN_REMOVES_UNIQUE = "page_fan_removes_unique",
  PAGE_FANS_BY_UNLIKE_SOURCE_UNIQUE = "page_fans_by_unlike_source_unique",
  //Page Video Views
  PAGE_VIDEO_VIEWS = "page_video_views",
  PAGE_VIDEO_VIEWS_BY_UPLOADED_HOSTED = "page_video_views_by_uploaded_hosted",
  PAGE_VIDEO_VIEWS_PAID = "page_video_views_paid",
  PAGE_VIDEO_VIEWS_ORGANIC = "page_video_views_organic",
  PAGE_VIDEO_VIEWS_BY_PAID_NON_PAID = "page_video_views_by_paid_non_paid",
  PAGE_VIDEO_VIEWS_AUTOPLAYED = "page_video_views_autoplayed",
  PAGE_VIDEO_VIEWS_CLICK_TO_PLAY = "page_video_views_click_to_play",
  PAGE_VIDEO_VIEWS_UNIQUE = "page_video_views_unique",
  PAGE_VIDEO_REPEAT_VIEWS = "page_video_repeat_views",
  PAGE_VIDEO_COMPLETE_VIEWS_30S = "page_video_complete_views_30s",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_PAID = "page_video_complete_views_30s_paid",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_ORGANIC = "page_video_complete_views_30s_organic",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_AUTOPLAYED = "page_video_complete_views_30s_autoplayed",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_CLICK_TO_PLAY = "page_video_complete_views_30s_click_to_play",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_UNIQUE = "page_video_complete_views_30s_unique",
  PAGE_VIDEO_COMPLETE_VIEWS_30S_REPEAT_VIEWS = "page_video_complete_views_30s_repeat_views",
  POST_VIDEO_COMPLETE_VIEWS_30S_AUTOPLAYED = "post_video_complete_views_30s_autoplayed",
  POST_VIDEO_COMPLETE_VIEWS_30S_CLICKED_TO_PLAY = "post_video_complete_views_30s_clicked_to_play",
  POST_VIDEO_COMPLETE_VIEWS_30S_ORGANIC = "post_video_complete_views_30s_organic",
  POST_VIDEO_COMPLETE_VIEWS_30S_PAID = "post_video_complete_views_30s_paid",
  POST_VIDEO_COMPLETE_VIEWS_30S_UNIQUE = "post_video_complete_views_30s_unique",
  PAGE_VIDEO_VIEWS_10S = "page_video_views_10s",
  PAGE_VIDEO_VIEWS_10S_PAID = "page_video_views_10s_paid",
  PAGE_VIDEO_VIEWS_10S_ORGANIC = "page_video_views_10s_organic",
  PAGE_VIDEO_VIEWS_10S_AUTOPLAYED = "page_video_views_10s_autoplayed",
  PAGE_VIDEO_VIEWS_10S_CLICK_TO_PLAY = "page_video_views_10s_click_to_play",
  PAGE_VIDEO_VIEWS_10S_UNIQUE = "page_video_views_10s_unique",
  PAGE_VIDEO_VIEWS_10S_REPEAT = "page_video_views_10s_repeat",
  PAGE_VIDEO_VIEW_TIME = "page_video_view_time",
  //Page Views
  PAGE_VIEWS_TOTAL = "page_views_total",
  PAGE_VIEWS_LOGOUT = "page_views_logout",
  PAGE_VIEWS_LOGGED_IN_TOTAL = "page_views_logged_in_total",
  PAGE_VIEWS_LOGGED_IN_UNIQUE = "page_views_logged_in_unique",
  PAGE_VIEWS_EXTERNAL_REFERRALS = "page_views_external_referrals",
  PAGE_VIEWS_BY_PROFILE_TAB_TOTAL = "page_views_by_profile_tab_total",
  PAGE_VIEWS_BY_PROFILE_TAB_LOGGED_IN_UNIQUE = "page_views_by_profile_tab_logged_in_unique",
  PAGE_VIEWS_BY_INTERNAL_REFERER_LOGGED_IN_UNIQUE = "page_views_by_internal_referer_logged_in_unique",
  PAGE_VIEWS_BY_SITE_LOGGED_IN_UNIQUE = "page_views_by_site_logged_in_unique",
  PAGE_VIEWS_BY_AGE_GENDER_LOGGED_IN_UNIQUE = "page_views_by_age_gender_logged_in_unique",
  PAGE_VIEWS_BY_REFERERS_LOGGED_IN_UNIQUE = "page_views_by_referers_logged_in_unique",
  //Page Video Posts
  POST_VIDEO_AVG_TIME_WATCHED = "post_video_avg_time_watched",
  POST_VIDEO_COMPLETE_VIEWS_ORGANIC = "post_video_complete_views_organic",
  POST_VIDEO_COMPLETE_VIEWS_ORGANIC_UNIQUE = "post_video_complete_views_organic_unique",
  POST_VIDEO_COMPLETE_VIEWS_PAID = "post_video_complete_views_paid",
  POST_VIDEO_COMPLETE_VIEWS_PAID_UNIQUE = "post_video_complete_views_paid_unique",
  POST_VIDEO_RETENTION_GRAPH = "post_video_retention_graph",
  POST_VIDEO_RETENTION_GRAPH_CLICKED_TO_PLAY = "post_video_retention_graph_clicked_to_play",
  POST_VIDEO_RETENTION_GRAPH_AUTOPLAYED = "post_video_retention_graph_autoplayed",
  POST_VIDEO_VIEWS_ORGANIC = "post_video_views_organic",
  POST_VIDEO_VIEWS_ORGANIC_UNIQUE = "post_video_views_organic_unique",
  POST_VIDEO_VIEWS_PAID = "post_video_views_paid",
  POST_VIDEO_VIEWS_PAID_UNIQUE = "post_video_views_paid_unique",
  POST_VIDEO_LENGTH = "post_video_length",
  POST_VIDEO_VIEWS = "post_video_views",
  POST_VIDEO_VIEWS_UNIQUE = "post_video_views_unique",
  POST_VIDEO_VIEWS_AUTOPLAYED = "post_video_views_autoplayed",
  POST_VIDEO_VIEWS_CLICKED_TO_PLAY = "post_video_views_clicked_to_play",
  POST_VIDEO_VIEWS_15S = "post_video_views_15s",
  POST_VIDEO_VIEWS_60S_EXCLUDES_SHORTER = "post_video_views_60s_excludes_shorter",
  POST_VIDEO_VIEWS_10S = "post_video_views_10s",
  POST_VIDEO_VIEWS_10S_UNIQUE = "post_video_views_10s_unique",
  POST_VIDEO_VIEWS_10S_AUTOPLAYED = "post_video_views_10s_autoplayed",
  POST_VIDEO_VIEWS_10S_CLICKED_TO_PLAY = "post_video_views_10s_clicked_to_play",
  POST_VIDEO_VIEWS_10S_ORGANIC = "post_video_views_10s_organic",
  POST_VIDEO_VIEWS_10S_PAID = "post_video_views_10s_paid",
  POST_VIDEO_VIEWS_10S_SOUND_ON = "post_video_views_10s_sound_on",
  POST_VIDEO_VIEWS_SOUND_ON = "post_video_views_sound_on",
  POST_VIDEO_VIEW_TIME = "post_video_view_time",
  POST_VIDEO_VIEW_TIME_ORGANIC = "post_video_view_time_organic",
  POST_VIDEO_VIEW_TIME_BY_AGE_BUCKET_AND_GENDER = "post_video_view_time_by_age_bucket_and_gender",
  POST_VIDEO_VIEW_TIME_BY_REGION_ID = "post_video_view_time_by_region_id",
  POST_VIDEO_VIEWS_BY_DISTRIBUTION_TYPE = "post_video_views_by_distribution_type",
  POST_VIDEO_VIEW_TIME_BY_DISTRIBUTION_TYPE = "post_video_view_time_by_distribution_type",
  POST_VIDEO_VIEW_TIME_BY_COUNTRY_ID = "post_video_view_time_by_country_id",
  //Stories
  PAGE_CONTENT_ACTIVITY_BY_ACTION_TYPE_UNIQUE = "page_content_activity_by_action_type_unique",
  PAGE_CONTENT_ACTIVITY_BY_AGE_GENDER_UNIQUE = "page_content_activity_by_age_gender_unique",
  PAGE_CONTENT_ACTIVITY_BY_CITY_UNIQUE = "page_content_activity_by_city_unique",
  PAGE_CONTENT_ACTIVITY_BY_COUNTRY_UNIQUE = "page_content_activity_by_country_unique",
  PAGE_CONTENT_ACTIVITY_BY_LOCALE_UNIQUE = "page_content_activity_by_locale_unique",
  PAGE_CONTENT_ACTIVITY = "page_content_activity",
  PAGE_CONTENT_ACTIVITY_BY_ACTION_TYPE = "page_content_activity_by_action_type",
  POST_ACTIVITY = "post_activity",
  POST_ACTIVITY_UNIQUE = "post_activity_unique",
  POST_ACTIVITY_BY_ACTION_TYPE = "post_activity_by_action_type",
  POST_ACTIVITY_BY_ACTION_TYPE_UNIQUE = "post_activity_by_action_type_unique",
  //Video Ad Breaks
  PAGE_DAILY_VIDEO_AD_BREAK_AD_IMPRESSIONS_BY_CROSSPOST_STATUS = "page_daily_video_ad_break_ad_impressions_by_crosspost_status",
  PAGE_DAILY_VIDEO_AD_BREAK_CPM_BY_CROSSPOST_STATUS = "page_daily_video_ad_break_cpm_by_crosspost_status",
  PAGE_DAILY_VIDEO_AD_BREAK_EARNINGS_BY_CROSSPOST_STATUS = "page_daily_video_ad_break_earnings_by_crosspost_status",
  POST_VIDEO_AD_BREAK_AD_IMPRESSIONS = "post_video_ad_break_ad_impressions",
  POST_VIDEO_AD_BREAK_EARNINGS = "post_video_ad_break_earnings",
  POST_VIDEO_AD_BREAK_AD_CPM = "post_video_ad_break_ad_cpm"
}

export enum FacebookInsightDatePreset {
  TODAY = "today",
  YESTERDAY = "yesterday",
  THIS_MONTH = "this_month",
  LAST_MONTH = "last_month",
  THIS_QUARTER = "this_quarter",
  MAXIMUM = "maximum",
  DATA_MAXIMUM = "data_maximum",
  LAST_3D = "last_3d",
  LAST_7D = "last_7d",
  LAST_14D = "last_14d",
  LAST_28D = "last_28d",
  LAST_30D = "last_30d",
  LAST_90D = "last_90d",
  LAST_WEEK_MON_SUN = "last_week_mon_sun",
  LAST_WEEK_SUN_SAT = "last_week_sun_sat",
  LAST_QUARTER = "last_quarter",
  LAST_YEAR = "last_year",
  THIS_WEEK_MON_TODAY = "this_week_mon_today",
  THIS_WEEK_SUN_TODAY = "this_week_sun_today",
  THIS_YEAR = "this_year",
}

export enum FacebookInsightPeriod {
  DAY = "day",
  WEEK = "week",
  DAYS_28 = "days_28",
  MONTH = "month",
  LIFETIME = "lifetime",
  TOTAL_OVER_RANGE = "total_over_range",
}

export const FacebookInsightMetricMapper: { metric: FacebookInsightMetric, period: FacebookInsightPeriod[] }[] = [
  { metric: FacebookInsightMetric.PAGE_TAB_VIEWS_LOGIN_TOP_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_TAB_VIEWS_LOGIN_TOP, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_TAB_VIEWS_LOGOUT_TOP, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_TOTAL_ACTIONS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_LOGGED_IN_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_BY_SITE_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_CTA_CLICKS_LOGGED_IN_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_CALL_PHONE_CLICKS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CALL_PHONE_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CALL_PHONE_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_CALL_PHONE_CLICKS_LOGGED_IN_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_CALL_PHONE_CLICKS_BY_SITE_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_GET_DIRECTIONS_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_GET_DIRECTIONS_CLICKS_LOGGED_IN_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_GET_DIRECTIONS_CLICKS_BY_SITE_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_WEBSITE_CLICKS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_WEBSITE_CLICKS_BY_AGE_GENDER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_WEBSITE_CLICKS_LOGGED_IN_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_WEBSITE_CLICKS_LOGGED_IN_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.PAGE_WEBSITE_CLICKS_BY_SITE_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ENGAGED_USERS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POST_ENGAGEMENTS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONSUMPTIONS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONSUMPTIONS_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONSUMPTIONS_BY_CONSUMPTION_TYPE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONSUMPTIONS_BY_CONSUMPTION_TYPE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKIN_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKIN_TOTAL_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKIN_MOBILE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKIN_MOBILE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKINS_BY_AGE_GENDER, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKINS_BY_LOCALE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_PLACES_CHECKINS_BY_COUNTRY, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_NEGATIVE_FEEDBACK, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_NEGATIVE_FEEDBACK_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_NEGATIVE_FEEDBACK_BY_TYPE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_NEGATIVE_FEEDBACK_BY_TYPE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSITIVE_FEEDBACK_BY_TYPE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSITIVE_FEEDBACK_BY_TYPE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_FANS_ONLINE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_ONLINE_PER_DAY, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FAN_ADDS_BY_PAID_NON_PAID_UNIQUE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_PAID_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_ORGANIC_V2, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_ORGANIC_UNIQUE_V2, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_VIRAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_VIRAL_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_NONVIRAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_NONVIRAL_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_STORY_TYPE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_STORY_TYPE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_LOCALE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_BY_AGE_GENDER_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_FREQUENCY_DISTRIBUTION, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_IMPRESSIONS_VIRAL_FREQUENCY_DISTRIBUTION, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_PAID_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_ORGANIC, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_ORGANIC_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_SERVED_IMPRESSIONS_ORGANIC_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_VIRAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_VIRAL_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_NONVIRAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_NONVIRAL_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_POSTS_IMPRESSIONS_FREQUENCY_DISTRIBUTION, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.POST_ENGAGED_USERS, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_NEGATIVE_FEEDBACK, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_NEGATIVE_FEEDBACK_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_NEGATIVE_FEEDBACK_BY_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_NEGATIVE_FEEDBACK_BY_TYPE_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_ENGAGED_FAN, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_CLICKS, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_CLICKS_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_CLICKS_BY_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_CLICKS_BY_TYPE_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_PAID, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_PAID_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_FAN, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_FAN_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_FAN_PAID, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_FAN_PAID_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_ORGANIC, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_ORGANIC_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_VIRAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_VIRAL_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_NONVIRAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_NONVIRAL_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_BY_STORY_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_IMPRESSIONS_BY_STORY_TYPE_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_LIKE_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_LOVE_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_WOW_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_HAHA_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_SORRY_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_ANGER_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_REACTIONS_BY_TYPE_TOTAL, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_LIKE_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_LOVE_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_WOW_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_HAHA_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_SORRY_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_ANGER_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_ACTIONS_POST_REACTIONS_TOTAL, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_LOCALE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_CITY, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_COUNTRY, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_GENDER_AGE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FAN_ADDS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FAN_ADDS_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_FANS_BY_LIKE_SOURCE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FANS_BY_LIKE_SOURCE_UNIQUE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FAN_REMOVES, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_FAN_REMOVES_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_FANS_BY_UNLIKE_SOURCE_UNIQUE, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_BY_UPLOADED_HOSTED, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_ORGANIC, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_BY_PAID_NON_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_AUTOPLAYED, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_CLICK_TO_PLAY, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_REPEAT_VIEWS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_ORGANIC, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_AUTOPLAYED, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_CLICK_TO_PLAY, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_COMPLETE_VIEWS_30S_REPEAT_VIEWS, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_30S_AUTOPLAYED, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_30S_CLICKED_TO_PLAY, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_30S_ORGANIC, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_30S_PAID, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_30S_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_PAID, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_ORGANIC, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_AUTOPLAYED, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_CLICK_TO_PLAY, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEWS_10S_REPEAT, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIDEO_VIEW_TIME, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_LOGOUT, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_LOGGED_IN_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_EXTERNAL_REFERRALS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_PROFILE_TAB_TOTAL, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_PROFILE_TAB_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_INTERNAL_REFERER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_SITE_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_AGE_GENDER_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_VIEWS_BY_REFERERS_LOGGED_IN_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK] },
  { metric: FacebookInsightMetric.POST_VIDEO_AVG_TIME_WATCHED, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_ORGANIC, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_ORGANIC_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_PAID, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_COMPLETE_VIEWS_PAID_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_RETENTION_GRAPH, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_RETENTION_GRAPH_CLICKED_TO_PLAY, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_RETENTION_GRAPH_AUTOPLAYED, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_ORGANIC, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_ORGANIC_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_PAID, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_PAID_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_LENGTH, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_UNIQUE, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_AUTOPLAYED, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_CLICKED_TO_PLAY, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_15S, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_60S_EXCLUDES_SHORTER, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_AUTOPLAYED, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_CLICKED_TO_PLAY, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_ORGANIC, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_PAID, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_10S_SOUND_ON, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_SOUND_ON, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME_ORGANIC, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME_BY_AGE_BUCKET_AND_GENDER, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME_BY_REGION_ID, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEWS_BY_DISTRIBUTION_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME_BY_DISTRIBUTION_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_VIDEO_VIEW_TIME_BY_COUNTRY_ID, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_ACTION_TYPE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_AGE_GENDER_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_CITY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_COUNTRY_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_LOCALE_UNIQUE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.PAGE_CONTENT_ACTIVITY_BY_ACTION_TYPE, period: [FacebookInsightPeriod.DAY, FacebookInsightPeriod.WEEK, FacebookInsightPeriod.DAYS_28] },
  { metric: FacebookInsightMetric.POST_ACTIVITY, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_ACTIVITY_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_ACTIVITY_BY_ACTION_TYPE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.POST_ACTIVITY_BY_ACTION_TYPE_UNIQUE, period: [FacebookInsightPeriod.LIFETIME] },
  { metric: FacebookInsightMetric.PAGE_DAILY_VIDEO_AD_BREAK_AD_IMPRESSIONS_BY_CROSSPOST_STATUS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_DAILY_VIDEO_AD_BREAK_CPM_BY_CROSSPOST_STATUS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.PAGE_DAILY_VIDEO_AD_BREAK_EARNINGS_BY_CROSSPOST_STATUS, period: [FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_AD_BREAK_AD_IMPRESSIONS, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_AD_BREAK_EARNINGS, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
  { metric: FacebookInsightMetric.POST_VIDEO_AD_BREAK_AD_CPM, period: [FacebookInsightPeriod.LIFETIME, FacebookInsightPeriod.DAY] },
]
export type FacebookInsightMetricMapper = typeof FacebookInsightMetricMapper